
import { NgModule } from '@angular/core';
import { CardModule, BreadcrumbModule, StepsModule, ToolbarModule, CalendarModule, ListboxModule, InputSwitchModule, TabViewModule, SpinnerModule, DropdownModule, ToastModule, ProgressBarModule, TreeTableModule, EditorModule, CheckboxModule, ButtonModule, ConfirmDialogModule, MultiSelectModule, ContextMenuModule, RadioButtonModule, OrderListModule, DataViewModule, PanelModule, OverlayPanelModule, SelectButtonModule, ToggleButtonModule, CarouselModule, OrganizationChartModule, SidebarModule, ProgressSpinnerModule, ChartModule, DialogModule, TreeModule } from 'primeng';
import {FullCalendarModule} from 'primeng/fullcalendar';
import {TableModule} from 'primeng/table';

@NgModule({
  imports:[
    // AppCardsModule,
    CardModule,
    BreadcrumbModule,
    StepsModule,
    ToolbarModule,
    CalendarModule,
    ListboxModule,
    InputSwitchModule,
    TabViewModule,
    SpinnerModule,
    DropdownModule,
    ToastModule,
    ProgressBarModule,
    TableModule,
    TreeTableModule,
    EditorModule,
    CheckboxModule,
    ButtonModule,
    ConfirmDialogModule,
    MultiSelectModule,
    ContextMenuModule,
    RadioButtonModule,
    OrderListModule,
    DataViewModule,
    PanelModule,
    OverlayPanelModule,
    SelectButtonModule,
    ToggleButtonModule,
    CarouselModule,
    OrganizationChartModule,
    SidebarModule,
    SpinnerModule,
    CardModule,
    ProgressSpinnerModule,
    FullCalendarModule,
    ProgressBarModule,
    ChartModule,
    DialogModule,TreeModule
  ],
  exports: [
    // AppCardsModule,
    CardModule,
    ListboxModule,
    BreadcrumbModule,
    StepsModule,
    ToolbarModule,
    CalendarModule,
    InputSwitchModule,
    TabViewModule,
    SpinnerModule,
    DropdownModule,
    ToastModule,
    ProgressBarModule,
    TableModule,
    TreeTableModule,
    EditorModule,
    CheckboxModule,
    ButtonModule,
    ConfirmDialogModule,
    MultiSelectModule,
    ContextMenuModule,
    RadioButtonModule,
    OrderListModule,
    DataViewModule,
    PanelModule,
    OverlayPanelModule,
    SelectButtonModule,
    ToggleButtonModule,
    CarouselModule,
    OrganizationChartModule,
    SidebarModule,
    SpinnerModule,
    ProgressSpinnerModule,
    FullCalendarModule,
    DialogModule,
    TreeModule
  ],

})
export class AppNgPrimeModule {}

    